"""Make releng_tooltool_files.size a BigInteger

Revision ID: 697dbab45f3f
Revises: 
Create Date: 2023-05-29 17:24:48.868951

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "697dbab45f3f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("releng_tooltool_files", schema=None) as batch_op:
        batch_op.alter_column("size", existing_type=sa.INTEGER(), type_=sa.BigInteger(), existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("releng_tooltool_files", schema=None) as batch_op:
        batch_op.alter_column("size", existing_type=sa.BigInteger(), type_=sa.INTEGER(), existing_nullable=False)

    # ### end Alembic commands ###
