"""Initial migration

Revision ID: 8029026f4e23
Revises:
Create Date: 2025-07-09 15:23:55.891969

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8029026f4e23"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "releng_tooltool_batches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uploaded", sa.DateTime(), nullable=False),
        sa.Column("author", sa.Text(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("releng_tooltool_batches", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_releng_tooltool_batches_uploaded"), ["uploaded"], unique=False)

    op.create_table(
        "releng_tooltool_files",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("sha512", sa.String(length=128), nullable=False),
        sa.Column("visibility", sa.Enum("public", "internal", name="visibility"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sha512"),
    )
    op.create_table(
        "releng_tooltool_batch_files",
        sa.Column("file_id", sa.Integer(), nullable=False),
        sa.Column("batch_id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["releng_tooltool_batches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["releng_tooltool_files.id"],
        ),
        sa.PrimaryKeyConstraint("file_id", "batch_id"),
    )
    op.create_table(
        "releng_tooltool_file_instances",
        sa.Column("file_id", sa.Integer(), nullable=False),
        sa.Column("region", sa.Enum("us-east-1", "us-west-1", "us-west-2", name="region"), nullable=False),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["releng_tooltool_files.id"],
        ),
        sa.PrimaryKeyConstraint("file_id", "region"),
    )
    op.create_table(
        "releng_tooltool_pending_upload",
        sa.Column("file_id", sa.Integer(), nullable=False),
        sa.Column("expires", sa.DateTime(), nullable=False),
        sa.Column("region", sa.Enum("us-east-1", "us-west-1", "us-west-2", name="region"), nullable=False),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["releng_tooltool_files.id"],
        ),
        sa.PrimaryKeyConstraint("file_id"),
    )
    with op.batch_alter_table("releng_tooltool_pending_upload", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_releng_tooltool_pending_upload_expires"), ["expires"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("releng_tooltool_pending_upload", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_releng_tooltool_pending_upload_expires"))

    op.drop_table("releng_tooltool_pending_upload")
    op.drop_table("releng_tooltool_file_instances")
    op.drop_table("releng_tooltool_batch_files")
    op.drop_table("releng_tooltool_files")
    with op.batch_alter_table("releng_tooltool_batches", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_releng_tooltool_batches_uploaded"))

    op.drop_table("releng_tooltool_batches")
    # ### end Alembic commands ###
